//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEZBELE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrewProject
    {
        public int ID { get; set; }
        public int CrewID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual Project Project { get; set; }
    }
}
