//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEZBELE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Is
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Is()
        {
            this.IsKullanici = new HashSet<IsKullanici>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public int OlusturanID { get; set; }
        public int SurecID { get; set; }
        public string IsAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Surec Surec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsKullanici> IsKullanici { get; set; }
    }
}
