//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEZBELE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsKullanici
    {
        public int ID { get; set; }
        public int IsID { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual Is Is { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
