//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEZBELE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MEZBELEEntities : DbContext
    {
        public MEZBELEEntities()
            : base("name=MEZBELEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Is> Is { get; set; }
        public virtual DbSet<IsKullanici> IsKullanici { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRol { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Proje> Proje { get; set; }
        public virtual DbSet<ProjeKullanici> ProjeKullanici { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Surec> Surec { get; set; }
    }
}
