//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEZBELE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Surec()
        {
            this.Is = new HashSet<Is>();
            this.Surec1 = new HashSet<Surec>();
        }
    
        public int ID { get; set; }
        public string SurecAdi { get; set; }
        public int ProjeID { get; set; }
        public Nullable<System.DateTime> BaslamaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<int> Sure { get; set; }
        public Nullable<int> TamamlanmaOrani { get; set; }
        public Nullable<int> Oncelik { get; set; }
        public int AnaSurecID { get; set; }
        public string Notlar { get; set; }
        public string Aciklama { get; set; }
        public int OlusturanKullaniciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Is> Is { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Proje Proje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surec> Surec1 { get; set; }
        public virtual Surec Surec2 { get; set; }
    }
}
